### ISSUE TITLE
Make mancenter service type to default to ClusterIP

### ISSUE THREAD

**Issue by xrow** [hazelcast/charts#146]
This is a minor security and configuration improvement. When setting the the Service type for the mancenter to Loadbalancer it open per default a Nodeport in the firewall. This could be consired a security risk even though you can change it to ClusterIP. The request is to set the mancenter default to type ClusterIP because it is also the kubernetes default.  

https://github.com/hazelcast/charts/blob/master/stable/hazelcast-enterprise/values.yaml#L336

**Comment by hasancelik** [comment]
Hi @xrow,

Thanks for pointed out. We preferred `LoadBalancer` for Management Center service because it provides ease of use when user tries to connect Management Center dashboard after chart deployment. As you said, it is configurable as well so if user wants to deploy the chart to production env or has security concerns, user can use another service type. 

On the other side, using `ClusterIP` as a default service type with some `kubectl port-forward` instructions at README can also be good approach, for example:
```
kubectl port-forward svc/<deployment-name>-hazelcast-mancenter 8080:8080
```
WDYT @leszko ?

**Comment by leszko** [comment]
I'm in line with what Hasan wrote. Meaning that we try to make the default configuration as simple as possible to the new users. So, I'd keep `LoadBalancer`.

**Comment by xrow** [comment]
Ok this is up to you. Please close.
