### ISSUE TITLE
resources parameters for cpu/memory

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/charts#34]
I see from this link that we can define 4 parameters for cpu/memory but README only mentions `resources` with a default value `nil`
https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#resource-requests-and-limits-of-pod-and-container

```
resources.limits.cpu
resources.limits.memory
resources.requests.cpu
resources.requests.memory
```

README has to be fixed by adding all those 4 parameters with their default values.

**Comment by leszko** [comment]
@mesutcelik I remember that one of the comments when we send a PR to the official repo was that we should not set any default values on resources, but keep them commented out (let user uncomment them if needed). That makes sense to me, because when you keep them `nil` by default then the values which are default for the Kubernetes cluster are used. Otherwise we would need to decide what are the default values for Hazelcast.

Wdyt?

**Comment by mesutcelik** [comment]
> That makes sense to me, because when you keep them nil by default then the values which are default for the Kubernetes cluster are used

I did not know that and the person who asked the question was not clear on that too. 

Can we add all those 4 parameters to the table and put `default` instead of `nil`? The table only contains `resources` for now.

**Comment by leszko** [comment]
Sure, send as #40
