### ISSUE TITLE
Management Center Ingress has no Path defined

### ISSUE THREAD

**Issue by sashkica** [hazelcast/charts#80]
The ingress does not work because the ingress path is not defined, the path should be set to:  /hazelcast-mancenter

**Comment by mesutcelik** [comment]
Hi @sashkica ,

What is the issue you are having? When you send a request to `/hazelcast-mancenter`, isn't it handled by MC Service? I haven't tried myself but path might have been removed because we only have one backing service behind Ingress and all requests are sent to that service

I see it was removed with that commit https://github.com/hazelcast/charts/pull/29/commits/92416971d655f2c9214e5857ddec0bb568768ed9 cc: @davidkarlsen

**Comment by sashkica** [comment]
Hi,
True it works! Having the /hazelcast-mancenter path defined in the ingress is just more convenient.
